# Default values for c#.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  pullPolicy: IfNotPresent
imagePullSecrets:
  name: acrjdk8s
service:
  name: dotnetcore
  type: LoadBalancer
  externalPort: 80
  internalPort: 5107
resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
ingress:
  enabled: false
